In [1]:
import pandas as pd
import numpy as np

# Card Data

In [149]:
# Import merged df
cards_df = pd.read_csv('./data/cards_merged.csv')
cards_df

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,3.0,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,1.0,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,2.0,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,2.0,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,1.0,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,Royal Delivery,28000018,NaN,3.0,common,NaN,787.0,spell,ground,both,splash,False,4.00,54.17
117,Void,28000023,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,0.80,53.83
118,Goblin Curse,28000024,NaN,2.0,epic,NaN,NaN,spell,ground,both,splash,False,1.28,52.53
119,Spirit Empress,28000025,NaN,6.0,legendary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Vines,28000026,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,NaN,NaN

In [150]:
# Count nulls
cards_clean_df = cards_df.copy()
cards_df.isnull().sum()

name                  0
id                    0
maxEvolutionLevel    73
elixirCost            1
rarity                0
damage11             29
hitpoints            20
type                  1
mobility              1
targets               1
attack_type           2
groupCard             1
usage                 2
Win Rate              2
dtype: int64

## Investigate `maxEvolutionLevel`

In [151]:
# maxEvolutionLevel values
cards_df[['name', 'maxEvolutionLevel']].head(10)

         name  maxEvolutionLevel
0      Knight                3.0
1     Archers                1.0
2     Goblins                2.0
3       Giant                2.0
4   P.E.K.K.A                1.0
5     Minions                NaN
6     Balloon                2.0
7       Witch                1.0
8  Barbarians                1.0
9       Golem                NaN

| maxEvolutionLevel | Trait |
| ----------------- | ----- |
| NaN | No trait |
| 1.0 | Evolution |
| 2.0 | Hero |
|3.0 | Evolution & Hero |

In [152]:
# Transform maxEvolutionLevel to categorical
cards_clean_df.rename(columns={'maxEvolutionLevel': 'wild'}, inplace=True)
cards_clean_df['wild'] = cards_df['maxEvolutionLevel'].replace({np.nan: 'normal', 1: 'evo', 2: 'hero', 3: 'both'})
cards_clean_df.head(10)

,name,id,wild,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,both,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,evo,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,hero,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,hero,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,evo,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61
5,Minions,26000005,normal,3.0,common,306.0,230.0,troop,flying,both,single,True,2.88,53.23
6,Balloon,26000006,hero,5.0,epic,960.0,1679.0,troop,flying,buildings,single,False,7.52,57.38
7,Witch,26000007,evo,5.0,epic,265.0,839.0,troop,ground,both,splash,False,5.12,49.92
8,Barbarians,26000008,evo,5.0,common,960.0,670.0,troop,ground,ground,single,True,0.32,50.35
9,Golem,26000009,normal,8.0,epic,312.0,5120.0,troop,ground,ground,single,False,2.24,57.26

In [153]:
cards_clean_df['wild'].isnull().sum()

np.int64(0)

## Investigate `damage11` and `hitpoints`

In [154]:
# Missing values in damage11 and hitpoints
cards_df.loc[(cards_df['damage11'].isnull()) | (cards_df['hitpoints'].isnull())]
# Missing damage11 is due to missing data
# Missing hitpoints is mostly due to spells not having health

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
31,Fire Spirit,26000031,NaN,1.0,common,NaN,230.0,troop,ground,ground,single,False,1.76,51.20
64,Firecracker,26000064,1.0,3.0,common,NaN,304.0,troop,ground,both,splash,False,8.08,50.15
65,Mighty Miner,26000065,NaN,4.0,champion,NaN,2250.0,troop,ground,ground,single,False,4.24,57.00
67,Battle Healer,26000068,NaN,4.0,rare,NaN,1717.0,troop,flying,ground,single,False,1.44,56.07
68,Skeleton King,26000069,NaN,4.0,champion,NaN,2298.0,troop,ground,ground,splash,False,3.68,57.40
69,Archer Queen,26000072,NaN,5.0,champion,NaN,1000.0,troop,ground,ground,single,False,6.48,56.47
70,Golden Knight,26000074,NaN,4.0,champion,NaN,1799.0,troop,ground,ground,single,False,1.68,50.69
71,Monk,26000077,NaN,5.0,champion,NaN,2150.0,troop,ground,ground,single,False,2.32,57.35
72,Skeleton Dragons,26000080,NaN,4.0,common,NaN,560.0,troop,flying,both,single,True,2.72,61.78
73,Mother Witch,26000083,NaN,4.0,legendary,NaN,529.0,troop,ground,ground,single,False,2.00,57.19
74,Electro Spirit,26000084,NaN,1.0,common,NaN,230.0,troop,ground,ground,single,False,6.40,55.94
75,Electro Giant,26000085,NaN,7.0,epic,NaN,3855.0,troop,ground,ground,splash,False,1.28,51.35
76,Phoenix,26000087,NaN,4.0,legendary,NaN,1052.0,troop,flying,both,single,False,1.60,58.40
77,Little Prince,26000093,NaN,3.0,champion,NaN,698.0,troop,ground,ground,single,False,1.76,52.56
78,Goblin Demolisher,26000095,NaN,4.0,rare,NaN,1300.0,troop,ground,ground,single,False,0.48,53.67
79,Goblin Machine,26000096,NaN,5.0,legendary,NaN,2304.0,troop,ground,ground,single,False,0.88,57.56
80,Suspicious Bush,26000097,NaN,2.0,rare,NaN,81.0,troop,ground,ground,single,False,1.12,54.43
81,Goblinstein,26000099,NaN,5.0,champion,NaN,721.0,troop,ground,ground,single,False,4.64,54.22
82,Rune Giant,26000101,NaN,4.0,epic,NaN,2508.0,troop,ground,ground,single,False,0.32,44.30
83,Berserker,26000102,NaN,2.0,common,NaN,896.0,troop,ground,ground,single,False,1.36,54.13
84,Boss Bandit,26000103,NaN,6.0,champion,NaN,2803.0,troop,ground,ground,single,False,4.32,54.60
97,Goblin Drill,27000013,1.0,4.0,epic,NaN,1313.0,building,ground,ground,single,False,1.92,51.49
98,Fireball,28000000,NaN,4.0,rare,242.0,NaN,spell,flying,both,splash,False,18.64,53.21
99,Arrows,28000001,NaN,3.0,common,294.0,NaN,spell,flying,both,splash,False,30.64,55.97
100,Rage,28000002,NaN,2.0,epic,0.0,NaN,spell,ground,both,splash,False,8.48,55.06
101,Rocket,28000003,NaN,6.0,rare,1484.0,NaN,spell,ground,both,splash,False,7.44,48.96
102,Goblin Barrel,28000004,1.0,3.0,epic,360.0,NaN,spell,ground,both,splash,False,10.80,48.82
103,Freeze,28000005,NaN,4.0,epic,41.0,NaN,spell,ground,both,splash,False,3.12,54.81
104,Mirror,28000006,NaN,NaN,epic,0.0,NaN,spell,both,both,NaN,False,1.84,44.18
105,Lightning,28000007,NaN,6.0,epic,1056.0,NaN,spell,ground,both,splash,False,7.04,56.03
106,Zap,28000008,1.0,2.0,common,192.0,NaN,spell,ground,both,splash,False,11.36,52.82
107,Poison,28000009,NaN,4.0,epic,256.0,NaN,spell,ground,both,splash,False,7.44,52.33
108,Graveyard,28000010,NaN,5.0,legendary,1296.0,NaN,spell,ground,both,splash,False,3.44,56.34
109,The Log,28000011,NaN,2.0,legendary,290.0,NaN,spell,ground,both,splash,False,42.88,52.50
110,Tornado,28000012,NaN,3.0,epic,168.0,NaN,spell,ground,both,splash,False,13.52,51.63
111,Clone,28000013,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,0.88,49.53
112,Earthquake,28000014,NaN,3.0,rare,888.0,NaN,spell,ground,both,splash,False,6.72,54.97
114,Heal Spirit,28000016,NaN,1.0,rare,NaN,230.0,spell,ground,both,splash,False,1.60,59.30
115,Giant Snowball,28000017,1.0,2.0,common,192.0,NaN,spell,ground,both,splash,False,2.24,53.08
116,Royal Delivery,28000018,NaN,3.0,common,NaN,787.0,spell,ground,both,splash,False,4.00,54.17
117,Void,28000023,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,0.80,53.83
118,Goblin Curse,28000024,NaN,2.0,epic,NaN,NaN,spell,ground,both,splash,False,1.28,52.53
119,Spirit Empress,28000025,NaN,6.0,legendary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Vines,28000026,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,NaN,NaN

In [155]:
# Replace missing values
cards_clean_df.rename(columns={'hitpoints': 'hitpoints11'}, inplace=True)
cards_clean_df.loc[31, 'damage11'] = 207
cards_clean_df.loc[64, 'damage11'] = 320
cards_clean_df.loc[65, 'damage11'] = 40
cards_clean_df.loc[67, 'damage11'] = 148
cards_clean_df.loc[68, 'damage11'] = 204
cards_clean_df.loc[69, 'damage11'] = 225
cards_clean_df.loc[70, 'damage11'] = 161
cards_clean_df.loc[71, 'damage11'] = 140
cards_clean_df.loc[72, 'damage11'] = 161
cards_clean_df.loc[73, 'damage11'] = 133
cards_clean_df.loc[74, 'damage11'] = 99
cards_clean_df.loc[75, 'damage11'] = 163
cards_clean_df.loc[76, 'damage11'] = 217
cards_clean_df.loc[77, 'damage11'] = 104
cards_clean_df.loc[78, 'damage11'] = 186
cards_clean_df.loc[79, 'damage11'] = 212
cards_clean_df.loc[80, 'damage11'] = 256
cards_clean_df.loc[81, 'damage11'] = 128
cards_clean_df.loc[82, 'damage11'] = 120
cards_clean_df.loc[83, 'damage11'] = 102
cards_clean_df.loc[84, 'damage11'] = 245
cards_clean_df.loc[97, 'damage11'] = 120
cards_clean_df.loc[100, 'damage11'] = 179
cards_clean_df.loc[111, 'damage11'] = 0
cards_clean_df.loc[114, 'damage11'] = 110
cards_clean_df.loc[116, 'damage11'] = 437
cards_clean_df.loc[117, 'damage11'] = 1020
cards_clean_df.loc[118, 'damage11'] = 210
cards_clean_df.loc[119, 'damage11'] = 307
cards_clean_df.loc[120, 'damage11'] = 306
cards_clean_df.loc[114, 'type'] = 'troop'
cards_clean_df.loc[119, 'hitpoints11'] = 1177
cards_clean_df['damage11'].isnull().sum()

np.int64(0)

## Investigate the rest of the missing values

In [156]:
# Missing values per column
cards_clean_df.isnull().sum()

name            0
id              0
wild            0
elixirCost      1
rarity          0
damage11        0
hitpoints11    19
type            1
mobility        1
targets         1
attack_type     2
groupCard       1
usage           2
Win Rate        2
dtype: int64

In [157]:
# Rows with missing values
cards_clean_df[cards_clean_df.isnull().any(axis=1)]

,name,id,wild,elixirCost,rarity,damage11,hitpoints11,type,mobility,targets,attack_type,groupCard,usage,Win Rate
98,Fireball,28000000,normal,4.0,rare,242.0,NaN,spell,flying,both,splash,False,18.64,53.21
99,Arrows,28000001,normal,3.0,common,294.0,NaN,spell,flying,both,splash,False,30.64,55.97
100,Rage,28000002,normal,2.0,epic,179.0,NaN,spell,ground,both,splash,False,8.48,55.06
101,Rocket,28000003,normal,6.0,rare,1484.0,NaN,spell,ground,both,splash,False,7.44,48.96
102,Goblin Barrel,28000004,evo,3.0,epic,360.0,NaN,spell,ground,both,splash,False,10.80,48.82
103,Freeze,28000005,normal,4.0,epic,41.0,NaN,spell,ground,both,splash,False,3.12,54.81
104,Mirror,28000006,normal,NaN,epic,0.0,NaN,spell,both,both,NaN,False,1.84,44.18
105,Lightning,28000007,normal,6.0,epic,1056.0,NaN,spell,ground,both,splash,False,7.04,56.03
106,Zap,28000008,evo,2.0,common,192.0,NaN,spell,ground,both,splash,False,11.36,52.82
107,Poison,28000009,normal,4.0,epic,256.0,NaN,spell,ground,both,splash,False,7.44,52.33
108,Graveyard,28000010,normal,5.0,legendary,1296.0,NaN,spell,ground,both,splash,False,3.44,56.34
109,The Log,28000011,normal,2.0,legendary,290.0,NaN,spell,ground,both,splash,False,42.88,52.50
110,Tornado,28000012,normal,3.0,epic,168.0,NaN,spell,ground,both,splash,False,13.52,51.63
111,Clone,28000013,normal,3.0,epic,0.0,NaN,spell,ground,both,splash,False,0.88,49.53
112,Earthquake,28000014,normal,3.0,rare,888.0,NaN,spell,ground,both,splash,False,6.72,54.97
115,Giant Snowball,28000017,evo,2.0,common,192.0,NaN,spell,ground,both,splash,False,2.24,53.08
117,Void,28000023,normal,3.0,epic,1020.0,NaN,spell,ground,both,splash,False,0.80,53.83
118,Goblin Curse,28000024,normal,2.0,epic,210.0,NaN,spell,ground,both,splash,False,1.28,52.53
119,Spirit Empress,28000025,normal,6.0,legendary,307.0,1177.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Vines,28000026,normal,3.0,epic,306.0,NaN,spell,ground,both,splash,False,NaN,NaN

In [158]:
# Mirror is a unique card so the values cannot be replaced; can be omitted during analysis
# Spirit Empress and vines are very new cards so the values need to be filled manually
cards_clean_df.loc[119, ['type', 'mobility', 'targets', 'attack_type', 'groupCard', 'usage', 'Win Rate']] = ['troop', 'flying', 'both', 'single', 'False', 4.80, 54.23]
cards_clean_df.loc[120, ['usage', 'Win Rate']] = [4.80, 53.21]

In [159]:
cards_clean_df.isnull().sum()

name            0
id              0
wild            0
elixirCost      1
rarity          0
damage11        0
hitpoints11    19
type            0
mobility        0
targets         0
attack_type     1
groupCard       0
usage           0
Win Rate        0
dtype: int64

In [160]:
cards_clean_df.drop(104).isnull().sum()

name            0
id              0
wild            0
elixirCost      0
rarity          0
damage11        0
hitpoints11    18
type            0
mobility        0
targets         0
attack_type     0
groupCard       0
usage           0
Win Rate        0
dtype: int64

## Export csv

In [161]:
cards_clean_df.drop(104).to_csv('./data/cards_cleaned.csv', index=False)
cards_clean_df.to_csv('./data/cards_cleaned_with_mirror.csv', index=False)

# Deck Data

In [2]:
# Import merged df
decks_df = pd.read_csv('./data/cards_merged.csv')
decks_df

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,3.0,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,1.0,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,2.0,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,2.0,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,1.0,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,Royal Delivery,28000018,NaN,3.0,common,NaN,787.0,spell,ground,both,splash,False,4.00,54.17
117,Void,28000023,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,0.80,53.83
118,Goblin Curse,28000024,NaN,2.0,epic,NaN,NaN,spell,ground,both,splash,False,1.28,52.53
119,Spirit Empress,28000025,NaN,6.0,legendary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Vines,28000026,NaN,3.0,epic,NaN,NaN,spell,ground,both,splash,False,NaN,NaN

In [ ]:
#